// Generated by CoffeeScript 1.4.0
(function() {
  var DemoFieldset, demo, fieldsets;

  fieldsets = [];

  demo = function(name, cb) {
    return fieldsets.push(new DemoFieldset(name, cb));
  };

  DemoFieldset = (function() {

    function DemoFieldset(name, launch_cb) {
      this.name = name;
      this.launch_cb = launch_cb;
      launch_cb.call(this);
    }

    DemoFieldset.prototype.build = function(into) {
      var pre,
        _this = this;
      pre = $('<pre>', {
        text: this.code
      });
      if (this.run != null) {
        $('<a>', {
          href: '#',
          text: 'Run',
          "class": 'btn btn-primary'
        }).css({
          float: 'right'
        }).click(function(e) {
          _this.run.call(_this);
          return e.preventDefault();
        }).appendTo(pre);
      }
      return into.append($('<legend>', {
        text: this.name
      })).append(pre);
    };

    return DemoFieldset;

  })();

  $(function() {
    var c, fs, _i, _len, _results;
    c = $('#main').empty();
    _results = [];
    for (_i = 0, _len = fieldsets.length; _i < _len; _i++) {
      fs = fieldsets[_i];
      _results.push(fs.build(c));
    }
    return _results;
  });

  demo("New Dataset", function() {
    return this.code = "var dataset = new bamboo.Dataset({id: '8db48e665fdc494ea69ab90d2aefc341'});";
  });

  demo("Get info", function() {
    return this.code = "dataset.query_info();";
  });

  demo("Add aggregation calculation(s)", function() {
    return this.code = "// ONLY RUN BELOW ONCE\n//dataset.add_calculation('wp_functional', 'newest(submit_date,functional)', 'wp_id');\n//dataset.add_calculation('latest_submit_date', 'max(submit_date)', 'wp_id');";
  });

  demo("Now get the aggregated dataset, and check its okay", function() {
    return this.code = "var aggregatedDatasets = dataset.query_aggregations();\nvar waterPointDataset = new bamboo.Dataset({id: aggregatedDatasets.aggregations[\"wp_id\"]});\nwaterPointDataset.query_info()";
  });

  demo("And finally.... get the data", function() {
    return this.code = "waterPointDataset.query_dataset()\nconsole.log(waterPointDataset.data)";
  });

}).call(this);
