// Generated by CoffeeScript 1.4.0
(function() {
  var DemoFieldset, demo, fieldsets;

  fieldsets = [];

  demo = function(name, cb) {
    return fieldsets.push(new DemoFieldset(name, cb));
  };

  DemoFieldset = (function() {

    function DemoFieldset(name, launch_cb) {
      this.name = name;
      this.launch_cb = launch_cb;
      launch_cb.call(this);
    }

    DemoFieldset.prototype.build = function(into) {
      var pre,
        _this = this;
      pre = $('<pre>', {
        text: this.code
      });
      if (this.run != null) {
        $('<a>', {
          href: '#',
          text: 'Run',
          "class": 'btn btn-primary'
        }).css({
          float: 'right'
        }).click(function(e) {
          _this.run.call(_this);
          return e.preventDefault();
        }).appendTo(pre);
      }
      return into.append($('<legend>', {
        text: this.name
      })).append(pre);
    };

    return DemoFieldset;

  })();

  $(function() {
    var c, fs, _i, _len, _results;
    c = $('#main').empty();
    _results = [];
    for (_i = 0, _len = fieldsets.length; _i < _len; _i++) {
      fs = fieldsets[_i];
      _results.push(fs.build(c));
    }
    return _results;
  });

  demo("New Dataset", function() {
    return this.code = "var dataset = new bamboo.Dataset({id: 'fa871c15b7cd4ab69f7c3bff83ac6107'});";
  });

  demo("Get info", function() {
    return this.code = "dataset.query_info();";
  });

  demo("Add aggregation calculation(s)", function() {
    return this.code = "dataset.query_calculations();\nif(dataset.calculations.length == 0) {\n    // ONLY ADD THE AGGREGATIONS ONCE\n    dataset.add_aggregations('ratio_polls_open', 'ratio(a_a in [\"1\"], 1)', ['governorate']);\n    dataset.add_aggregations('ballots_counted', 'ratio(b_e in [\"1\"],1)', ['governorate']);\n    dataset.add_aggregations('ballot_boxes_empty_before_voting', 'ratio(b_g in [\"1\"],1)', ['governorate']);\n    dataset.add_aggregations('ballot_boxes_closed_with_HEC_seal', 'ratio(b_h in [\"1\"],1)', ['governorate']);\n    dataset.add_aggregations('polling_center_handycap_accessible', 'ratio(b_j in [\"1\"],1)', ['governorate']);\n    dataset.add_aggregations('polling_center_have_indelible_ink', 'ratio(b_k in [\"1\"],1)', ['governorate']);\n\n}";
  });

  demo("Now get the aggregated dataset, and check its okay", function() {
    return this.code = "var aggregatedDatasets = dataset.query_aggregations();\nvar electionDataset = new bamboo.Dataset({id: aggregatedDatasets.aggregations[\"governorate\"]});";
  });

}).call(this);
