// Generated by CoffeeScript 1.4.0
(function() {
  var callAjax, test_data;

  test_data = {
    csv_file: "https://www.dropbox.com/s/0m8smn04oti92gr/sample_dataset_school_survey.csv?dl=1"
  };

  callAjax = function(xhrSettings) {
    var method, response;
    method = xhrSettings.type ? xhrSettings.type : "GET";
    try {
      response = mock_data.urls[xhrSettings.url][method];
      xhrSettings.success.call(null, response);
    } catch (err) {
      xhrSettings.error.call();
    }
  };

  describe("Bamboo API", function() {
    beforeEach(function() {
      if (bamboo.settings.URL.match(/^http/)) {
        spyOn($, 'ajax').andCallThrough();
      } else {
        spyOn($, 'ajax').andCallFake(callAjax);
      }
    });
    it("can create from url", function() {
      var dataset;
      dataset = new bamboo.Dataset({
        url: test_data.csv_file,
        autoload: true
      });
      expect(dataset.id).toBeDefined();
      expect(dataset.query_info().info.id).toBe(dataset.id);
    });
    it("can delete by dataset id", function() {
      var dataset, deleted;
      dataset = new bamboo.Dataset({
        url: test_data.csv_file,
        autoload: true
      });
      expect(dataset.id).toBeDefined();
      deleted = dataset["delete"]();
      expect(deleted).toBeTruthy();
    });
    it("can check if dataset exists", function() {
      var dataset, exists;
      dataset = new bamboo.Dataset({
        url: test_data.csv_file,
        autoload: true
      });
      expect(dataset.id).toBeDefined();
      exists = bamboo.dataset_exists(dataset.id);
      expect(exists).toBeTruthy();
      exists = bamboo.dataset_exists("some-none-existsent-id");
      expect(exists).toBeFalsy();
    });
    describe("Query", function() {
      var dataset, loaded;
      loaded = false;
      dataset = void 0;
      beforeEach(function() {
        dataset = new bamboo.Dataset({
          url: test_data.csv_file,
          autoload: false
        });
        runs(function() {
          dataset.load_from_url(false, function() {
            return loaded = true;
          });
        });
        waitsFor(function() {
          return loaded;
        }, "dataset to load", 1000);
      });
      afterEach(function() {
        var deleted;
        deleted = dataset["delete"]();
        expect(deleted).toBeTruthy();
      });
      it("can query info", function() {
        expect(dataset.query_info().info.id).toBe(dataset.id);
        expect(dataset.info.num_rows).toBe(14);
      });
      it("can query data", function() {
        expect(dataset.data).not.toBeDefined();
        dataset.query_dataset();
        expect(dataset.data).toBeDefined();
      });
      it("can select from dataset", function() {
        var select;
        select = dataset.select({
          grade: 1
        });
        expect(select.length).toBe(14);
      });
      it("can run a filter query", function() {
        var query1;
        query1 = dataset.query({
          grade: 4
        });
        expect(query1.length).toBe(7);
      });
      it("can get the summary", function() {
        var group, select, summary;
        summary = dataset.summary();
        expect(dataset.summary_result).toBeDefined();
        select = {
          "grade": 1
        };
        summary = dataset.summary(select);
        expect(dataset._summaries["summary_" + (JSON.stringify(select))]).toBeDefined();
        group = "sex";
        summary = dataset.summary(select, group);
        expect(dataset._summaries["summary_" + (JSON.stringify(select)) + "_" + group]).toBeDefined();
      });
    });
  });

}).call(this);
