// Generated by CoffeeScript 1.4.0
(function() {
  var callAjax, test_data;

  test_data = {
    csv_file: "https://www.dropbox.com/s/0m8smn04oti92gr/sample_dataset_school_survey.csv?dl=1"
  };

  callAjax = function(xhrSettings) {
    var method;
    method = xhrSettings.type ? xhrSettings.type : "GET";
    xhrSettings.success.call(null, mock_data.urls[xhrSettings.url][method]);
  };

  describe("Bamboo API", function() {
    beforeEach(function() {
      if (bamboo.settings.URL.match(/^http/)) {
        spyOn($, 'ajax').andCallThrough();
      } else {
        spyOn($, 'ajax').andCallFake(callAjax);
      }
    });
    it("can create from url", function() {
      var dataset;
      dataset = new bamboo.Dataset({
        url: test_data.csv_file,
        autoload: true
      });
      expect(dataset.id).toBeDefined();
      expect(dataset.query_info().info.id).toBe(dataset.id);
    });
    describe("Query", function() {
      var dataset, loaded;
      loaded = false;
      dataset = void 0;
      beforeEach(function() {
        dataset = new bamboo.Dataset({
          url: test_data.csv_file,
          autoload: false
        });
        runs(function() {
          dataset.load_from_url(false, function() {
            return loaded = true;
          });
        });
        waitsFor(function() {
          return loaded;
        }, "dataset to load", 1000);
      });
      afterEach(function() {
        var deleted;
        deleted = dataset["delete"]();
        expect(deleted).toBeTruthy();
      });
      it("can query info", function() {
        expect(dataset.query_info().info.id).toBe(dataset.id);
        expect(dataset.info.num_rows).toBe(14);
      });
    });
  });

}).call(this);
