// Generated by CoffeeScript 1.4.0

/*
This is a shortcut for "console.log" that prevents
the call from breaking in browsers where console is
not defined.
*/


(function() {
  var __slice = [].slice;

  this.log = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if ((typeof console !== "undefined" && console !== null) && (console.log != null)) {
      return console.log.apply(console, args);
    }
  };

}).call(this);
