// Generated by CoffeeScript 1.3.3
(function() {
  var DemoFieldset, demo, fieldsets;

  fieldsets = [];

  demo = function(name, cb) {
    return fieldsets.push(new DemoFieldset(name, cb));
  };

  DemoFieldset = (function() {

    function DemoFieldset(name, launch_cb) {
      this.name = name;
      this.launch_cb = launch_cb;
      launch_cb.call(this);
    }

    DemoFieldset.prototype.build = function(into) {
      var pre,
        _this = this;
      pre = $('<pre>', {
        text: this.code
      });
      if (this.run != null) {
        $('<a>', {
          href: '#',
          text: 'Run',
          "class": 'btn btn-primary'
        }).css({
          float: 'right'
        }).click(function(e) {
          _this.run.call(_this);
          return e.preventDefault();
        }).appendTo(pre);
      }
      return into.append($('<legend>', {
        text: this.name
      })).append(pre);
    };

    return DemoFieldset;

  })();

  $(function() {
    var c, fs, _i, _len, _results;
    c = $('#main').empty();
    _results = [];
    for (_i = 0, _len = fieldsets.length; _i < _len; _i++) {
      fs = fieldsets[_i];
      _results.push(fs.build(c));
    }
    return _results;
  });

  demo("New Dataset", function() {
    return this.code = "var dataset = new bamboo.Dataset({url: 'http://bitly.com/ZfzBwP'});";
  });

  demo("Check if dataset exists", function() {
    return this.code = "bamboo.dataset_exists('nonexistentdataset_id');";
  });

  demo("Get info", function() {
    return this.code = "dataset.query_info();";
  });

  demo("Add calculation", function() {
    return this.code = "dataset.add_calculation(\"above_3rd_grade\", \"grade > 3\");\ndataset.query_dataset();\nconsole.log(dataset.data);";
  });

}).call(this);
