// Generated by CoffeeScript 1.3.3

/*
$ = $ || throw new Error('jquery not included')
*/


(function() {
  var BAMBOO_URL, Dataset, getData;

  BAMBOO_URL = "http://bamboo.io/datasets";

  Dataset = (function() {

    function Dataset(data, cb) {
      if ('url' in data) {
        this.load_from_url(data.url);
      } else if ('id' in data) {
        this.load_from_id(data.id);
      } else if ('path' in data) {
        this.load_from_id(data.path);
      }
    }

    Dataset.prototype.load_from_url = function(url) {
      var fail_cb, return_value, success_cb,
        _this = this;
      return_value = false;
      success_cb = function(returned_data) {
        return _this.id = JSON.parse(returned_data).id;
      };
      fail_cb = function(a, b, c) {
        return console.log("Fail", a, b, c);
      };
      return $.ajax({
        url: BAMBOO_URL,
        type: 'POST',
        data: {
          url: url
        },
        async: false
      }).success(success_cb).fail(fail_cb);
    };

    Dataset.prototype.load_from_id = function(id) {
      return this.id = id;
    };

    Dataset.prototype.load_from_path = function(path) {};

    return Dataset;

  })();

  getData = (function() {

    function getData(columns, querys) {}

    return getData;

  })();

  this.bamboo = {
    Dataset: Dataset
  };

}).call(this);
